return {
  -- "nvim-treesitter/nvim-treesitter",
  -- opts = {
  --   ensure_installed = {
  --     "bash",
  --     "css",
  --     "html",
  --     "helm",
  --     "javascript",
  --     "json",
  --     "lua",
  --     "markdown",
  --     "markdown_inline",
  --     "python",
  --     "terraform",
  --     "tsx",
  --     "typescript",
  --     "vim",
  --     "yaml",
  --   },
  -- },
}
